//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopupApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopupApp_Own
    {
        public int PopupApp_Own_id { get; set; }
        public Nullable<int> PopupApp_Treaty_id { get; set; }
    
        public virtual PopupApp_Treaty PopupApp_Treaty { get; set; }
    }
}
