//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopupApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopupApp_Counterparty
    {
        public int PopupApp_Counterparty_id { get; set; }
        public string PopupApp_Counterparty_FIO { get; set; }
        public string PopupApp_Counterparty_Services { get; set; }
        public string PopupApp_Counterparty_Location { get; set; }
    }
}
