//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopupApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopupApp_Treaty
    {
        public int PopupApp_Treaty_id { get; set; }
        public string PopupApp_Treaty_Name { get; set; }
        public string PopupApp_Treaty_Location { get; set; }
        public string PopupApp_Treaty_Start_Date { get; set; }
        public string PopupApp_Treaty_End_Date { get; set; }
        public string PopupApp_Treaty_Coming { get; set; }
        public string PopupApp_Treaty_Counterparty { get; set; }
        public string PopupApp_Treaty_File_Name { get; set; }
        public byte[] PopupApp_Treaty_File { get; set; }
        public string PopupApp_Treaty_Cost { get; set; }
        public string PopupApp_Treaty_Status { get; set; }
    }
}
