//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopupApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopupApp_User
    {
        public int PopupApp_User_id { get; set; }
        public string PopupApp_User_Login { get; set; }
        public string PopupApp_User_Password { get; set; }
    }
}
